# Generated by Django 4.1.2 on 2022-11-06 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('payment_form', models.CharField(max_length=255)),
                ('payment_ammount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_type', models.CharField(max_length=255)),
                ('transaction_id', models.IntegerField()),
                ('inventory', models.CharField(max_length=255)),
                ('payment_sum', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
