# Generated by Django 4.1.2 on 2022-10-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='inventory',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='payment_sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
