# Generated by Django 4.1.2 on 2022-11-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_remove_customerinfo_schedule_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='schedule_date',
            field=models.DateField(),
        ),
    ]
