# Generated by Django 4.1.2 on 2022-10-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('schedule_date', models.IntegerField()),
                ('payment_form', models.CharField(max_length=255)),
                ('payment_ammount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('inventory_add', models.CharField(max_length=255)),
                ('inventory_remove', models.CharField(max_length=255)),
            ],
        ),
    ]
